### ISSUE TITLE
Words are missing diaereses

### ISSUE THREAD

**Issue by lemtom** [lemtom/statenvertaling#2]
List:
[missingdiaereses.txt](https://github.com/lemtom/statenvertaling/files/1847246/missingdiaereses.txt)

**Comment by DavidHaslam** [comment]
Was this a deficiency in the base text exported from a CrossWire published SWORD module **DutSVV** ?

Did the issue relate to the 66 protocanonical books _only_?

**Comment by DavidHaslam** [comment]
@lemtom 

Here's one you missed...
```
Isaiah 7:14: Daarom zal de Heere Zelf ulieden een teken geven; ziet, een maagd zal zwanger worden, en zij zal een Zoon baren, en Zijn naam IMMANUEL heten.
```
The capitalised word should be `IMMANUËL`

**Comment by DavidHaslam** [comment]
Useful reference article: [Dutch orthography](https://en.wikipedia.org/wiki/Dutch_orthography#Diaeresis)
