### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by LAfricain** [lemtom/statenvertaling#4]
Hello Tom,
This is not actually a bug report, but I couldn't find a way to get in touch with you. I was very happy to discover your work with the SVT. I work with the Crosswire module team and I tried to solve some issues with the [dutSVV module](https://gitlab.com/crosswire-bible-society/dutsvv). I was looking for both, Apocrypha and notes (dutKant in the crosswire repo).
I would like to use your file if possible and clone it on our gitlab repo. And I would like to change the link to the source for your git instance. I also created usfm files if you are interresting, even if you did all the work on the osis, usfm is easy to work on it.
I live in Belgium too. Lavaux-St-Anne (Rochefort).

Thank you for you help

**Comment by DavidHaslam** [comment]
Hi @lemtom ,

I too am a CrossWire volunteer. 

We require clarification about the **provenance** of the base text in `STV.xml` (ignoring added features such as Strong's).

Was the text exported from an earlier version of SWORD module **DutSVV** published by CrossWire?

If so, then Cyrille's plan to use your text runs into a difficulty.

CrossWire has a strict policy that prevents us using a source text that was exported wholly or in part from one of our modules.

This is because we require provenance for a TextSource that does not involve any circularity.

Kind regards,

David Haslam

**Comment by lemtom** [comment]
I only got notified of this when David Haslam replied to other issues. Apparently newly opened issues didn't trigger an e-mail notification.

I was unable to successfully extract the text from the SWORD module, so I worked with verse-per-line text files given to me by an acquaintance in a chat group. As I understood it, they were formatted to be read by a commandline tool saved in an ascii format.

I assume the text was scraped from a website at some point, but I do not know which one. I scraped the apocryphal books myself from [this site](https://www.statenvertaling.net/apocriefen.html) and I assume this to be the origin of (or sharing a origin with) the text files as well (and probably most additional copies of the text available online). That site dates the text to an edition from 1888.

**Comment by lemtom** [comment]
@LAfricain I have sent an e-mail to the Gmail address I found while searching through the mailing lists.

**Comment by lemtom** [comment]
In hindsight, given your location, I probably should have connected the dots and sent it to the other e-mail address I found? 😳

**Comment by DavidHaslam** [comment]
@lemtom 

Thanks for the clarification. 

I think we will be able to demonstrate that there are sufficient differences between the text of CrossWire's earlier **DutSVV** module and your text to conclude that they are from independent transcriptions.

We can do a detailed comparison that will enable you to check yours against the appropriate "dead tree" reference edition at each location that differs.
