### ISSUE TITLE
Error line 4785 and 6042 and in the beginning of the file

### ISSUE THREAD

**Issue by LAfricain** [lemtom/statenvertaling#5]
When checking the validity of the STV.xml, I found this issues:
```
DutSVVA.osis.xml:4785: element reference: Schemas validity error : Element '{http://www.bibletechnologies.net/2003/OSIS/namespace}reference', attribute 'osisRef': '[1Co.10.8' is not a valid value of the atomic type '{http://www.bibletechnologies.net/2003/OSIS/namespace}osisRefRegex'.
```
The correct text should be:
`[<reference osisRef="1Co.10.8">1Co 10:8</reference> ]`
Again line 6042, `Italics` should be `italic`

And in the beginning of the file  `<work osiswork=` should be`<work osisWork=`

**Comment by DavidHaslam** [comment]
Prior to that, checking the **XML syntax** failed because of duplicate attribute names on line 6:
```
  <osisText osisRefWork="Bible"  osisRefWork="defaultReferenceScheme" osisIDWork="STV" xml:lang="nl">
```

Removing `osisRefWork="defaultReferenceScheme"` enables the XML to pass syntax check.

**Comment by LAfricain** [comment]
>Prior to that, checking the XML syntax failed because of duplicate attribute names on line 6

Correct, actually I did the correction on my merge xml file (svv and svva)

**Comment by lemtom** [comment]
This should be resolved by now.
